In [1]:
import numpy as np

<h1>Problem 1 </h1>

In [2]:
arr1=np.array([])

In [3]:
arr2=np.ones((4,2))

arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
arr3 = np.full(3,2)
arr3

array([2, 2, 2])

In [5]:
arr4=np.zeros_like(arr2)
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
arr5=np.ones_like(arr4)
arr5

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
new_list=[1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

<h1>Problem 2</h1>

In [8]:
arr6=np.arange(10,49)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [9]:
arr7 = np.array([[1,2,3],
                 [3,7,4],
                 [1,0,7]])
arr7.shape

(3, 3)

In [10]:
arr8=np.eye(3,3)
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr9=np.random.random(30)
arr9.mean()

0.5245904458636662

In [12]:
arr10=np.random.rand(10,10)

In [13]:
arr10.min()

0.00030770362610876845

In [14]:
arr10.max()

0.9885804160385909

In [15]:
arr11=np.zeros(10)

In [16]:
arr11[5]=1

In [17]:
arr11

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [18]:
arr12=np.array([[12,90,11],
               [13,89,16],
               [15,78,61]])
arr12

array([[12, 90, 11],
       [13, 89, 16],
       [15, 78, 61]])

In [84]:
arr12[2,1]=1

In [86]:
arr12

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [142]:
arr13=[1,2,0,0,4,0]
reversed=arr13[::-1]  
reversed

[0, 4, 0, 0, 2, 1]

<h1>Problem 3</h1>

In [173]:
x = np.array([[1,2],[3,5]])  
y = np.array([[5,6],[7,8]])
v = np.array([9,10]) 
w = np.array([11,12])

sum1=x+y
sum2=v+w

sub1=x-y
sub2=v-w

multi1=2*(x)
multi2=2*(y)
multi3=2*(v)
multi4=2*(w)

dot1=np.dot(v,w)
dot2=np.dot(x,v)
dot3=np.dot(x,y)

conc1=np.concatenate((x,y),axis=1)
conc1

conc2=np.concatenate((v,w), axis=0)
conc2


array([ 9, 10, 11, 12])

<h1>Problem 4</h1>

In [189]:
A = np.array([[3,4],[7,8]]) 
B = np.array([[5,3],[2,1]])

inverse=np.linalg.inv(A)
mult=np.dot(A,inverse)

Equal1=np.dot(A,B)
Equal2=np.dot(B,A)
Equal3=Equal1==Equal2

inverse1=np.transpose(Equal1)
inverse2=np.transpose(B)
inverse3=np.transpose(A)
inverse4=np.dot(inverse2,inverse3)

In [179]:
mult

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [185]:
Equal3

array([[False, False],
       [False, False]])

In [191]:
inverse1==inverse4

array([[ True,  True],
       [ True,  True]])

In [222]:
array=np.array([[2,-3,1],
                [1,-1,2],
                [3,1,-1]])
array1=np.array([-1,-3,9]).reshape(3,1)

inve=np.linalg.inv(array)

ans=np.dot(inve,array1)



                 

In [224]:
ans

array([[ 2.],
       [ 1.],
       [-2.]])